!cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
      PARAMETER(NI=55,NJ=55,NK=55,NFMAX=10,NZMAX=10,NP=11)
      CHARACTER*18 TITLE
      CHARACTER*64 HEADER,PRINTF,PLOTF
      COMMON F(NI,NJ,NK,NFMAX),P(NI,NJ,NK),RHO(NI,NJ,NK),GAM(NI,NJ,NK),&
     & CON(NI,NJ,NK),AIP(NI,NJ,NK),AIM(NI,NJ,NK),AJP(NI,NJ,NK),&
     & AJM(NI,NJ,NK),AKP(NI,NJ,NK),AKM(NI,NJ,NK),AP(NI,NJ,NK),&
     & IBLOCK(NI,NJ,NK),X(NI),XDIF(NI),XU(NI),XCV(NI),XCVS(NI),XCVI(NI),&
     & XCVIP(NI),Y(NJ),YDIF(NJ),YV(NJ),YCV(NJ),YCVS(NJ),YCVJ(NJ),&
     & YCVJP(NJ),Z(NK),ZDIF(NK),ZW(NK),ZCV(NK),ZCVS(NK),ZCVK(NK),&
     & ZCVKP(NK),R(NJ),RV(NJ),SX(NJ),SXMN(NJ),YCVR(NJ),YCVRS(NJ),&
     & YCDJ(NJ),YCDJP(NJ),ARX(NJ,NK),ARZ(NI,NJ),FOLD(NI,NJ,NK,NFMAX),&
     & PTX(NI),QTX(NI),PTY(NJ),QTY(NJ),PTZ(NK),QTZ(NK),EX(NI),HX(NI),&
     & GX(NI),PX(NI),QX(NI),RX(NI),&
     & FLUXI1(NJ,NK,NFMAX),FLUXL1(NJ,NK,NFMAX),FLUXJ1(NI,NK,NFMAX),&
     & FLUXM1(NI,NK,NFMAX),FLUXK1(NI,NJ,NFMAX),FLUXN1(NI,NJ,NFMAX),&
     & KBCI1(NJ,NK),KBCL1(NJ,NK),KBCJ1(NI,NK),KBCM1(NI,NK),KBCK1(NI,NJ),&
     & KBCN1(NI,NJ),FLXCI1(NJ,NK),FLXCL1(NJ,NK),FLXCJ1(NI,NK),&
     & FLXCM1(NI,NK),FLXCK1(NI,NJ),FLXCN1(NI,NJ),FLXPI1(NJ,NK),&
     & FLXPL1(NJ,NK),FLXPJ1(NI,NK),FLXPM1(NI,NK),FLXPK1(NI,NJ),&
     & FLXPN1(NI,NJ)
      COMMON/GENL/NF,L1,L2,L3,M1,M2,M3,N1,N2,N3,IST,JST,KST,ITER,SMALL,&
     & BIG,LAST,TIME,DT,MODE,KORD,KOUT,IU1,IU2,KPGR,KSTOP,TOL,&
     & NPTI,IPTM,KEPR,KEPL,KCY
      COMMON/NFF/RELAX(NP),KPRINT(NP),IXYZ(NP),KSOLVE(NFMAX),&
     & KBLOC(NFMAX),NTIMES(NFMAX),NTC(NFMAX),CRIT(NFMAX),&
     & IBORX(NFMAX),IBORY(NFMAX),IBORZ(NFMAX),IPUN(NFMAX)
      COMMON DU(NI,NJ,NK),DV(NI,NJ,NK),DW(NI,NJ,NK),FV(NJ),FVP(NJ),&
     &       FX(NI),FXM(NI),FY(NJ),FYM(NJ),FZ(NK),FZM(NK)
      COMMON/SORC/SMAX,SSUM
      COMMON/COEF/FLOW,DIFF,ACOF
      COMMON/TTL/TITLE(NP),HEADER,PRINTF,PLOTF
      COMMON/EZG/NCVLX,NCVLY,NCVLZ,XL,YL,ZL,POWERX,POWERY,POWERZ
      COMMON/ZG/NZX,NZY,NZZ,NCVX(NZMAX),NCVY(NZMAX),NCVZ(NZMAX),&
     & XZONE(NZMAX),YZONE(NZMAX),ZZONE(NZMAX),POWRX(NZMAX),POWRY(NZMAX),&
     & POWRZ(NZMAX)
      DIMENSION U(NI,NJ,NK),V(NI,NJ,NK),W(NI,NJ,NK)
      EQUIVALENCE (F(1,1,1,1),U(1,1,1)),(F(1,1,1,2),V(1,1,1)),&
     & (F(1,1,1,3),W(1,1,1))
      DIMENSION SC(NI,NJ,NK),SP(NI,NJ,NK)
      EQUIVALENCE (CON,SC),(AP,SP)
      DIMENSION PC(NI,NJ,NK),T(NI,NJ,NK)
      EQUIVALENCE (F(1,1,1,4),PC(1,1,1)),(F(1,1,1,5),T(1,1,1))
