def generate_f90(config_structure):
    f90_lines = ["! Generated by PrePRODIC3D"]

    # HEADER section
    header = config_structure.get("HEADER", {})
    for key, value in header.items():
        f90_lines.append(f"      {key}='{value}'")

    # GRID section
    grid = config_structure.get("GRID", {})
    if grid:
        f90_lines.append("      ENTRY GRID")
        mode = grid.get("MODE", 1)  # Default to 1 if not specified
        f90_lines.append(f"         MODE={mode}")
        # Add more parameters from GRID section as needed

    # You can add more sections here as your application requires
    # ...

    return "\n".join(f90_lines)
